#!/bin/tcsh

#setenv OMP_NUM_THREADS 2

date

# T21
#./puma.x 32 10
mpiexec -np 2 puma.x 32 10

# T42
#./puma.x 64 10
#mpiexec -np 4 puma.x 64 10

# T85
#./puma.x 128 10
#mpiexec -np 4 puma.x 128 10

# T179
#./puma.x 256 10
#mpiexec -np 4 puma.x 256 10

date

set outpath = output
rm -rf $outpath
mkdir $outpath
mv output_* $outpath

set ncpath  = netcdf
rm -rf $ncpath
mkdir $ncpath

foreach var (ps u v div vor t)
   set fctl = $outpath/output_$var.ctl
   set fbin = $outpath/output_$var.bin
   set fnc  = $ncpath/output_$var.nc
   cdo -f nc import_binary $fctl $fnc
   echo "producing ... $fnc"
end
