#!/bin/tcsh

setenv CONVERT_NC 1           # 修改这里 switch for converting binary: 1 to netcdf; 0 off
setenv KEEP_BIN   0           # 修改这里 if you want to keep raw outputs?

./pkugcm.x

if ($CONVERT_NC == 1) then

   setenv NLEV  10            # 修改这里 number of levels
   setenv NLAT  32            # 修改这里 number of latitudes (T21=32, T42=64, T85=128, T170=256)
   setenv NTIME 360

   setenv VARID t
   setenv VARDS Temperature
   setenv VARUN K
   echo " "
   ncl bin2nc.ncl

   setenv VARID u
   setenv VARDS "Zonal Wind"
   setenv VARUN m/s
   echo " "
   ncl bin2nc.ncl

   setenv VARID v
   setenv VARDS "Meridional Wind"
   setenv VARUN m/s
   echo " "
   ncl bin2nc.ncl

   setenv VARID z
   setenv VARDS "Geopotential Height"
   setenv VARUN gpm
   echo " "
   ncl bin2nc.ncl

   setenv VARID ps
   setenv VARDS "Surface Pressure"
   setenv VARUN hPa
   setenv NLEV  1
   echo " "
   ncl bin2nc.ncl

   # MOVE RAW BINARY
   if ($KEEP_BIN == 1) then
      set outpath = output
      rm -rf $outpath
      mkdir $outpath
      mv output_*.bin $outpath
   else
      rm -f output_*.bin
   endif

   # MOVE NETCDF
   set ncpath  = netcdf
   rm -rf $ncpath
   mkdir $ncpath
   mv output_*.nc $ncpath

endif
