#!/bin/tcsh

setenv OMP_NUM_THREADS 2

date

# T21
./pkugcm.x 32 10

# T42
#./pkugcm.x 64 10

# T85
#./pkugcm.x 128 10

# T170
#./pkugcm.x 256 10

date

set outpath = output
rm -rf $outpath
mkdir $outpath
mv output_* $outpath

set ncpath  = netcdf
rm -rf $ncpath
mkdir $ncpath

foreach var (ps u v div vor t)
   set fctl = $outpath/output_$var.ctl
   set fbin = $outpath/output_$var.bin
   set fnc  = $ncpath/output_$var.nc
   cdo -f nc import_binary $fctl $fnc
   echo "writting ... $fnc"
end

